/**
 * Blog Pipeline → Payload CMS Bridge
 *
 * When your AI pipeline generates a blog, use this bridge to persist it in Payload.
 * Payload auto-generates the REST + GraphQL API for client developers.
 *
 * Usage in blog-automation.ts:
 *   import { saveBlogToPayload } from "@/payload/blog-bridge";
 *   await saveBlogToPayload({ title, body, excerpt, ... }, tenantId);
 */

import { getPayload } from "payload";
import config from "@/payload.config";
import type { GeneratedBlog } from "@/lib/saas-core/services/blog-automation";

interface SaveBlogParams {
  title: string;
  slug: string;
  excerpt: string;
  body: string;          // HTML string
  seoTitle: string;
  seoDescription: string;
  tags: string[];
  qualityScore?: number;
  competitorCount?: number;
  topic: string;
  tenantId: string;
}

export async function saveBlogToPayload(
  params: SaveBlogParams,
): Promise<{ id: string } | { error: string }> {
  try {
    const payload = await getPayload({ config });

    // Convert HTML body to Payload's Lexical rich text format
    // For now, store as a simple HTML block — Payload supports custom blocks
    const doc = await payload.create({
      collection: "blogs",
      data: {
        title: params.title,
        slug: params.slug,
        excerpt: params.excerpt,
        body: htmlToLexicalJson(params.body),
        seoTitle: params.seoTitle,
        seoDescription: params.seoDescription,
        tags: params.tags,
        status: "published",
        tenant: params.tenantId,
        qualityScore: params.qualityScore ?? 0,
        competitorCount: params.competitorCount ?? 0,
        topicSearched: params.topic,
        publishedAt: new Date().toISOString(),
      },
    });

    console.log(`[payload-bridge] Blog saved: ${doc.id} — "${params.title}"`);
    return { id: String(doc.id) };
  } catch (err: any) {
    console.error(`[payload-bridge] Failed to save blog: ${err.message}`);
    return { error: err.message };
  }
}

/**
 * Convert HTML string to Payload Lexical JSON format.
 * This is a simplified converter — for production, use a proper HTML→Lexical parser.
 */
function htmlToLexicalJson(html: string): any {
  // Strip HTML tags and create simple paragraph nodes
  const text = html.replace(/<[^>]*>/g, "").trim();
  const paragraphs = text.split(/\n{2,}/).filter(p => p.trim());

  if (paragraphs.length === 0) {
    return {
      root: {
        type: "root",
        format: "",
        indent: 0,
        version: 1,
        children: [{
          type: "paragraph",
          format: "",
          indent: 0,
          version: 1,
          children: [{ type: "text", text, format: 0, indent: 0, version: 1 }],
        }],
        direction: "ltr",
      },
    };
  }

  return {
    root: {
      type: "root",
      format: "",
      indent: 0,
      version: 1,
      children: paragraphs.map(p => ({
        type: "paragraph",
        format: "",
        indent: 0,
        version: 1,
        children: [{ type: "text", text: p, format: 0, indent: 0, version: 1 }],
      })),
      direction: "ltr",
    },
  };
}

/**
 * Get blogs via Payload REST API — for client developers.
 * This is auto-generated by Payload; no code needed.
 *
 * Endpoint: GET /api/payload/blogs?where[tenant][equals]=TENANT_ID
 * Headers: Authorization: users API-Key YOUR_API_KEY
 *
 * Example:
 *   curl "https://yourapp.com/api/payload/blogs?where[tenant][equals]=tenant_123" \
 *     -H "Authorization: users API-Key sa_xxx"
 */
