/**
 * Payload import map — generated by Payload, auto-updated.
 * Must exist at this path for the admin UI to load its client bundles.
 */

import { importMap as payloadImportMap } from "@payloadcms/next/importMap";
export const importMap = payloadImportMap;
